# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f0949aef94671a0863cf80adcd48afd2e07fd571b1315f16d37d4b5055e1acfae6c7873795569d8eea946b8375822bd0325f5fb9aae1b0afcbbe7fa77e76e423

test:
  secret_key_base: f32db6f95c883ff67fa8203a7ec6cdb04d4bdbb6d8ac25575b56c87993aaf219771c84c3d2ea266a05d29635851acd75d9b3d01bc8617b538172080e00a812b1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
